const historyQuizData = [
  // 1. 고조선 ~ 초기 국가
  { period: "고조선 ~ 초기 국가", name: "단군왕검", time: "기원전 2333년", description: "우리나라 최초의 국가 고조선 건국" },
  { period: "고조선 ~ 초기 국가", name: "주몽", time: "기원전 37년", description: "고구려 건국 (동명성왕)" },
  { period: "고조선 ~ 초기 국가", name: "온조", time: "기원전 18년", description: "백제 건국" },
  { period: "고조선 ~ 초기 국가", name: "박혁거세", time: "기원전 57년", description: "신라 건국" },
  { period: "고조선 ~ 초기 국가", name: "김수로", time: "42년", description: "철이 풍부했던 금관가야 건국" },

  // 2. 삼국 시대
  { period: "삼국 시대", name: "태조왕", time: "1~2세기", description: "고구려 기틀 마련, 옥저 정복" },
  { period: "삼국 시대", name: "소수림왕", time: "4세기", description: "고구려 불교 수용, 태학 설립" },
  { period: "삼국 시대", name: "광개토 대왕", time: "4~5세기", description: "고구려 영토를 만주 벌판까지 크게 넓힘" },
  { period: "삼국 시대", name: "장수왕", time: "5세기", description: "평양 천도, 한강 유역 차지 (남진 정책)" },
  { period: "삼국 시대", name: "을지문덕", time: "612년", description: "살수대첩에서 수나라 군대를 크게 무찌름" },
  { period: "삼국 시대", name: "연개소문", time: "7세기", description: "고구려 최고 권력자, 당나라 침입에 강경하게 맞섬" },
  { period: "삼국 시대", name: "양만춘", time: "645년", description: "안시성 전투에서 당나라 대군을 물리침" },
  { period: "삼국 시대", name: "근초고왕", time: "4세기", description: "백제 전성기 이끎 (해외 진출, 칠지도 하사)" },
  { period: "삼국 시대", name: "무령왕", time: "6세기", description: "지방에 22담로 설치, 벽돌무덤(무령왕릉)을 남김" },
  { period: "삼국 시대", name: "성왕", time: "6세기", description: "사비 천도, 국호를 남부여로 고치고 중흥 노력" },
  { period: "삼국 시대", name: "계백", time: "660년", description: "황산벌에서 5천 결사대로 신라군에 맞서 끝까지 싸움" },
  { period: "삼국 시대", name: "지증왕", time: "6세기", description: "국호 '신라' 확정, 우산국 정벌" },
  { period: "삼국 시대", name: "이사부", time: "512년", description: "지증왕의 명령으로 우산국(울릉도) 정벌" },
  { period: "삼국 시대", name: "법흥왕", time: "6세기", description: "신라 불교 공인, 율령 반포" },
  { period: "삼국 시대", name: "이차돈", time: "527년", description: "신라 불교 공인을 위해 기꺼이 순교함" },
  { period: "삼국 시대", name: "진흥왕", time: "6세기", description: "신라 전성기, 화랑도 개편, 한강 유역 차지" },
  { period: "삼국 시대", name: "원효", time: "7세기", description: "불교를 백성들에게 쉽게 알리고 대중화하는 데 힘씀 (해골물 일화)" },
  { period: "삼국 시대", name: "선덕 여왕", time: "7세기", description: "신라 최초의 여왕, 첨성대와 황룡사 9층 목탑 건립" },
  { period: "삼국 시대", name: "김춘추", time: "7세기", description: "나당 연합 결성, 백제를 멸망시킴 (무열왕)" },
  { period: "삼국 시대", name: "김유신", time: "7세기", description: "화랑 출신 장군으로 신라의 삼국 통일에 큰 공을 세움" },
  { period: "삼국 시대", name: "문무왕", time: "676년", description: "당나라를 몰아내고 삼국 통일 완성" },

  // 3. 남북국 시대
  { period: "남북국 시대", name: "신문왕", time: "7세기", description: "통일 신라 왕권 강화, 9주 5소경 체제 정비" },
  { period: "남북국 시대", name: "장보고", time: "9세기", description: "청해진 설치, 동아시아 해상 무역 장악" },
  { period: "남북국 시대", name: "최치원", time: "9세기", description: "신라 6두품 출신 천재 학자, 당나라 빈공과 급제" },
  { period: "남북국 시대", name: "대조영", time: "698년", description: "옛 고구려 땅에 발해 건국 (고구려 계승)" },

  // 4. 후삼국 ~ 고려 시대
  { period: "후삼국 ~ 고려 시대", name: "견훤", time: "900년", description: "완산주(전주)에 후백제 건국" },
  { period: "후삼국 ~ 고려 시대", name: "궁예", time: "901년", description: "송악(개성)에 후고구려 건국" },
  { period: "후삼국 ~ 고려 시대", name: "왕건", time: "918년", description: "고려 건국 후 후삼국 통일 (태조)" },
  { period: "후삼국 ~ 고려 시대", name: "광종", time: "10세기", description: "노비안검법과 과거제 실시로 왕권 강화" },
  { period: "후삼국 ~ 고려 시대", name: "성종", time: "10세기", description: "최승로의 시무 28조 수용, 유교 정치 실시" },
  { period: "후삼국 ~ 고려 시대", name: "서희", time: "993년", description: "거란의 1차 침입 때 외교 담판으로 강동 6주 획득" },
  { period: "후삼국 ~ 고려 시대", name: "강감찬", time: "1019년", description: "거란의 3차 침입 때 귀주에서 대승리 (귀주 대첩)" },
  { period: "후삼국 ~ 고려 시대", name: "윤관", time: "12세기", description: "별무반 조직, 여진 정벌하고 동북 9성 쌓음" },
  { period: "후삼국 ~ 고려 시대", name: "묘청", time: "1135년", description: "서경(평양) 천도를 주장하며 난을 일으킴" },
  { period: "후삼국 ~ 고려 시대", name: "김부식", time: "12세기", description: "우리나라에서 가장 오래된 역사서 '삼국사기' 편찬" },
  { period: "후삼국 ~ 고려 시대", name: "지눌", time: "12~13세기", description: "수선사 결사 운동을 통해 타락한 불교 정화 노력" },
  { period: "후삼국 ~ 고려 시대", name: "최충헌", time: "12~13세기", description: "무신 정권의 최고 권력자, 교정도감 설치" },
  { period: "후삼국 ~ 고려 시대", name: "김윤후", time: "1232년", description: "처인성 전투에서 몽골 장수 살리타를 활로 쏘아 사살" },
  { period: "후삼국 ~ 고려 시대", name: "일연", time: "13세기", description: "우리 민족의 신화와 역사를 담은 '삼국유사' 편찬" },
  { period: "후삼국 ~ 고려 시대", name: "공민왕", time: "14세기", description: "반원 자주 정책 실시, 잃어버린 영토 회복 노력" },
  { period: "후삼국 ~ 고려 시대", name: "문익점", time: "14세기", description: "원나라에서 붓대 속에 목화씨를 몰래 숨겨 옴" },
  { period: "후삼국 ~ 고려 시대", name: "최무선", time: "14세기", description: "화통도감 설치, 우리나라 최초의 화약 무기 개발" },
  { period: "후삼국 ~ 고려 시대", name: "정도전", time: "14세기", description: "이성계를 도와 조선 건국 주도, 한양 도성 설계" },
  { period: "후삼국 ~ 고려 시대", name: "이성계", time: "1392년", description: "위화도 회군 후 고려를 무너뜨리고 조선 건국 (태조)" },
  { period: "후삼국 ~ 고려 시대", name: "정몽주", time: "14세기", description: "고려에 끝까지 충성하다 선죽교에서 죽음" },

  // 5. 조선 시대 전기~중기
  { period: "조선 시대 전기~중기", name: "이방원", time: "15세기", description: "호패법 실시 등 조선 초기 왕권 강화 기틀 마련 (태종)" },
  { period: "조선 시대 전기~중기", name: "세종 대왕", time: "1443년", description: "훈민정음 창제, 과학 기술 발전과 4군 6진 개척" },
  { period: "조선 시대 전기~중기", name: "장영실", time: "15세기", description: "자격루(물시계), 앙부일구(해시계) 등 과학 기구 발명" },
  { period: "조선 시대 전기~중기", name: "이종무", time: "1419년", description: "왜구의 근거지인 쓰시마섬(대마도) 정벌" },
  { period: "조선 시대 전기~중기", name: "김종서", time: "15세기", description: "두만강 유역에 6진 개척 (조선 영토 확장)" },
  { period: "조선 시대 전기~중기", name: "세조", time: "15세기", description: "조카 단종을 내쫓고 왕이 됨, 직전법 실시" },
  { period: "조선 시대 전기~중기", name: "성종", time: "15세기", description: "조선의 기본 법전인 '경국대전' 완성" },
  { period: "조선 시대 전기~중기", name: "조광조", time: "16세기", description: "급진적 개혁 정치를 시도하다 쫓겨남 (기묘사화)" },
  { period: "조선 시대 전기~중기", name: "이황", time: "16세기", description: "조선 성리학 발전에 큰 공헌, 도산 서원 건립" },
  { period: "조선 시대 전기~중기", name: "이이", time: "16세기", description: "현실적인 개혁 주장, 십만 양병설 제안" },
  { period: "조선 시대 전기~중기", name: "신사임당", time: "16세기", description: "시와 그림에 뛰어난 예술가, 율곡 이이의 어머니" },
  { period: "조선 시대 전기~중기", name: "허난설헌", time: "16세기", description: "뛰어난 글솜씨를 가졌던 조선 중기의 천재 여성 시인" },
  { period: "조선 시대 전기~중기", name: "이순신", time: "1592년", description: "임진왜란 때 거북선과 뛰어난 전술로 바다를 지킴" },
  { period: "조선 시대 전기~중기", name: "곽재우", time: "1592년", description: "임진왜란 때 붉은 옷을 입고 최초로 의병을 일으킴 (홍의장군)" },
  { period: "조선 시대 전기~중기", name: "권율", time: "1593년", description: "행주 대첩에서 치열한 전투 끝에 일본군을 크게 물리침" },
  { period: "조선 시대 전기~중기", name: "류성룡", time: "16세기", description: "임진왜란을 반성하며 기록한 책 '징비록' 저술" },
  { period: "조선 시대 전기~중기", name: "광해군", time: "17세기", description: "명과 후금 사이에서 중립 외교 실시, 동의보감 편찬 지원" },
  { period: "조선 시대 전기~중기", name: "허준", time: "1610년", description: "조선의 의학을 집대성한 세계적인 의학 서적 '동의보감' 완성" },
  { period: "조선 시대 전기~중기", name: "안용복", time: "17세기", description: "일본으로 건나가 울릉도와 독도가 조선의 영토임을 확인받음" },

  // 6. 조선 시대 후기
  { period: "조선 시대 후기", name: "효종", time: "17세기", description: "병자호란의 치욕을 씻기 위해 청나라를 치자는 북벌 운동 추진" },
  { period: "조선 시대 후기", name: "숙종", time: "17~18세기", description: "상평통보 전국 유통, 영토 확정을 위해 백두산정계비 건립" },
  { period: "조선 시대 후기", name: "영조", time: "18세기", description: "붕당의 대립을 막기 위해 탕평책 실시, 균역법 시행" },
  { period: "조선 시대 후기", name: "정조", time: "18세기", description: "규장각 육성, 수원 화성 건설 (조선 후기 문화 부흥 이끎)" },
  { period: "조선 시대 후기", name: "정약용", time: "18~19세기", description: "거중기 발명, 실학을 집대성함 (목민심서 저술)" },
  { period: "조선 시대 후기", name: "박지원", time: "18세기", description: "청나라를 다녀온 후 '열하일기' 저술, 상공업 발전 강조" },
  { period: "조선 시대 후기", name: "김홍도", time: "18세기", description: "씨름, 서당 등 서민들의 삶을 생생하게 그린 풍속화가" },
  { period: "조선 시대 후기", name: "신윤복", time: "18세기", description: "양반들의 풍류와 여성들의 모습을 섬세하게 그린 화가" },
  { period: "조선 시대 후기", name: "김정희", time: "19세기", description: "독창적인 글씨체인 추사체 창안, '세한도' 그림" },
  { period: "조선 시대 후기", name: "홍경래", time: "1811년", description: "세도 정치와 평안도 차별에 반발하여 대규모 농민 봉기 주도" },
  { period: "조선 시대 후기", name: "김정호", time: "19세기", description: "직접 전국을 돌아다니며 정밀한 지도인 '대동여지도' 제작" },
  { period: "조선 시대 후기", name: "김만덕", time: "18~19세기", description: "전 재산을 풀어 굶주린 제주도 백성들을 구한 여성 거상" },

  // 7. 개항기 ~ 일제 강점기
  { period: "개항기 ~ 일제 강점기", name: "흥선 대원군", time: "19세기", description: "서원 철폐, 외세 배척을 위해 전국에 척화비 건립" },
  { period: "개항기 ~ 일제 강점기", name: "명성 황후", time: "1895년", description: "러시아를 끌어들여 일본을 견제하려다 일본 자객에게 시해당함 (을미사변)" },
  { period: "개항기 ~ 일제 강점기", name: "전봉준", time: "1894년", description: "탐관오리에 맞서 동학 농민 운동 이끎 (녹두장군)" },
  { period: "개항기 ~ 일제 강점기", name: "서재필", time: "1896년", description: "독립협회 창립, 최초의 민간 신문 '독립신문' 창간" },
  { period: "개항기 ~ 일제 강점기", name: "안창호", time: "20세기", description: "신민회 조직 및 학교 설립 등 애국 계몽 운동과 독립운동 전개" },
  { period: "개항기 ~ 일제 강점기", name: "주시경", time: "20세기", description: "일제의 탄압 속에서도 우리말과 한글을 연구하고 지키는 데 힘씀" },
  { period: "개항기 ~ 일제 강점기", name: "안중근", time: "1909년", description: "중국 하얼빈역에서 이토 히로부미를 사살하여 민족의 독립 의지 알림" },
  { period: "개항기 ~ 일제 강점기", name: "유관순", time: "1919년", description: "천안 아우내 장터에서 만세 운동 주도하다 순국함" },
  { period: "개항기 ~ 일제 강점기", name: "김구", time: "20세기", description: "대한민국 임시 정부 주석, 한인 애국단 조직하여 독립운동 주도" },
  { period: "개항기 ~ 일제 강점기", name: "이봉창", time: "1932년", description: "일본 도쿄에서 일왕이 탄 마차에 폭탄을 던짐" },
  { period: "개항기 ~ 일제 강점기", name: "윤봉길", time: "1932년", description: "상하이 훙커우 공원에서 폭탄을 던져 일본군 고위 장성들 처단" },
  { period: "개항기 ~ 일제 강점기", name: "홍범도", time: "1920년", description: "봉오동 전투에서 일본군을 유인해 크게 무찌름" },
  { period: "개항기 ~ 일제 강점기", name: "김좌진", time: "1920년", description: "청산리 대첩에서 일본군을 상대로 독립군 최대의 승리를 거둠" },
  { period: "개항기 ~ 일제 강점기", name: "방정환", time: "1923년", description: "'어린이'라는 말을 널리 쓰고 어린이날을 제정함" },

  // 8. 대한민국 현대
  { period: "대한민국 현대", name: "이승만", time: "1948년", description: "대한민국 정부 수립 후 초대 대통령 취임" },
  { period: "대한민국 현대", name: "박정희", time: "1960~70년대", description: "경제 개발 5개년 계획 추진 및 경부 고속 국도 건설로 경제 성장 주도" },
  { period: "대한민국 현대", name: "전태일", time: "1970년", description: "노동자들의 열악한 근무 환경 개선을 요구하며 스스로 목숨을 바침" },
  { period: "대한민국 현대", name: "김대중", time: "2000년", description: "평양에서 최초의 남북 정상 회담 개최, 노벨 평화상 수상" }
];